### PR TITLE
Review README.md

### PR DESCRIPTION
**Pull request by cleherny**
## What
Review of the README file for `proj-roadsurf`.

## Comments
_Introduction:_ 
- I think you should specify that 2 methods were developed: machine learning (statistical analysis) and deep learning (road segmentation) and give the performance for both methods.
- You have obtained a single F1 score for the 3 datasets?

_Folder structure:_
- What do you mean by “One-time scripts”.
- I would add all the levels including the files/script names in order to add a short description of the purpose of each element.

_Workflow:_
- I would remove the simplified diagram.
- Consider adding 2 workflows: one for Machine Learning and one for Deep Learning.

_Other uses:_
- The name of the section “Other uses” should be changed.

_Preprocessing:_
- Add a sentence to explain the global aim of the scripts present in this folder.
- In the section Preprocessing, the 1st sentence should be reworked to not start by “Here”.
- What the script “correct_gt.py” is doing?

_Machine learning:_
- As mentioned above, I would add the workflow instructions of the Machine learning as a subsection of the workflow section.
- I would not mention here that we developed Deep Learning approach because Machine learning was not providing satisfying results.

_Other:_
- Add a Contributors section and maybe a License section.

### CODE REVIEW

**Comment by GwenaelleSa** [comment]
I applied the changes directly one the `gs/rewrite_readme` branch.

_Introduction_:
- Specify that 2 methods were developed: done
- Give the performance for the 2 methods: there is no performance for the machine learning algorithm since, in the end, we did not perform a classification with it.
- Single F1 score for the 3 dataset: yes, but I will change that (just not now because I don't have the right data under my hand).

_Folder structure_:
- one-time script: the script you generally only need once, but I just erased that info. That's cleaner.
- add all levels including the files: I would not, I think it is too heavy and there are the diagrams if people want to know what the scripts do.

_Workflow_:
- Remove the simplfied diagram: done
- consider adding 2 workflows: I prefer to keep only the functional algorithm in the workflow part.

_Other uses_: I agree, but I don't really know what to put instead. How to express that this part is to explain the preprocessing and the procedure we tried but that did not work? Would "additional uses" do?

_Preprocessing_:
- A sentence to explain the global aim: I modified the intro of this part.
- Not start with "here": deleted
- correct_gt.py: it was a one-shot to apply the feedback on the GT we got from our beneficiaries. Maybe I should delete it or put it into the `sandbox` folder.

_Machine learning_: Why would you not mention that it is not providing satisfying results? Is it too specific to our case?

_Other_:
- The contributors are listed on the side of the repository under "Contributors". I think it is needless to add them to the readme.
- The licence is given in the "about" section and there is a file for that, so I don't think it is necessary to repeat it in the readme.

Thank you for your review :)

**Comment by cleherny** [comment]
_Introduction_:
- You can add the link to the object-detector: "...the STDL's object detector"

_Folder structure_:
- I still think you should add at least the *.py files with a short description to give people a good overview of where they can find scripts.

_Machine learning workflow_:
Rephrasing: "The road shapes, initially provided as vector lines were transformed to polygon labels to fit the real extent of the road pixels in images. Then, a model was trained to classify roads in 2 classes (natural or artificial) with the STDL's object detector. Finally, the results were assessed. The entire procedure is illustrated in the diagram below."

_Other uses_:
- Yes "additional uses" or "additional applications" or "additional functionalities"

_Preprocessing_:
- Change the title to "Image preprocessing"
- Rephrasing: "The WTMS link in the `config_od.py` file refers to the [SWISSIMAGE 10 cm](https://www.swisstopo.admin.ch/en/geodata/images/ortho/swissimage10.html) product available online. However, better results are obtained using the [SWISSIMAGE RS] product (https://www.swisstopo.admin.ch/en/geodata/images/ortho/swissimage-rs.html). These data are available on request from swisstopo and require specific data processing to obtain tiles managed by a WMTS-type service (cf documentation)."

_Machine learning procedure_
- Rephrasing: "A supervised classification of road cover using a statistical approach was attempted. However, the results obtained in our case were not satisfactory as no significant statistical differences between the classes were found. The procedure is using [SWISSIMAGE RS] product (https://www.swisstopo.admin.ch/en/geodata/images/ortho/swissimage-rs.html) and is described below."

_correct_gt.py_: yes you might move it to sandbox. 

_config_preprocessing_:
- There is paths that seems to be very specific to our VM + mix of windows and ubuntu paths.

_config_od.yaml and prepare_data_od.py_:
- suffix "od" might be obscure for people as it is not obvious it is referring to the object-detector.

**Comment by cleherny** [comment]
## What
Review of the readme file for `data`.

## Comments
- "All the initial georeferenced data **are** available in the crs EPSG:2053. "

_Area of interest_:
- Rephrasing: The model was trained on 2 tiles of the AOI and tested on the 2 other tiles.

_Quarry_:
- Rephrasing: The quarries were obtained from our project for [quarries detection](https://github.com/swiss-territorial-data-lab/proj-dqry). It is also possible...
- Add link to the data url

_siwssTLM3D_:
- Add link to the data url

_Road parameters_:
- Rephrasing: The parameters used for the road processing were defined depending on the class(es) of interest and by iterations for the road width. 
- by iterations for the road width: add the different width ranges in parenthesis?

_Images_:
- The images swissIMAGE 10 cm are available at the link given in the config files:
   - Add the link here
   - The link is provided in `config_od.yaml` only, in `config_stats.yaml` titiler link is provided
- Rephrasing: The images swissIMAGE RS can be ordered from swisstopo and need to be preprocessed as described here (link to main README.md). Both product**s** are described on the swisstopo dedicated webpage.

**Comment by GwenaelleSa** [comment]
I did the modifications on my branch. I think we can close this pull request.

**Comment by cleherny** [comment]
I did another read of the branch `gs/rewrite_readme` and I have minor comments:

_Main README_:
- Introduction: I would add the link to the object detector: "The algorithm has an approach based on deep learning using the STDL's object detector."
- Folder structure: you can replace |- by |_ symbol when the arborescence is not going further. You can also delete | if not needed.
- Machine learning workflow: remove 'here' from 'here below'.

_Data README_:
- Data: "All the initial georeferenced data **are** available"
- AOI: Replace "and to test it on a new one" with "and to test it on another one."
- Quarries: Replace "The quarries were defined in our project for quarries detection" with "The quarries are a result of our project of automatic quarry detection"
- Road parameter: although this is not wrong, it is much more common to use the term 'processing' rather than 'treatment' when talking about data handling (this last term is also suitable).
- Images: "Both product**s** are described on the swisstopo dedicated webpage."

**Comment by GwenaelleSa** [comment]
Noted, I will do

**Pull request closed without merging**
